var subject = require('./mystery.js')
var mock = require('mock-fs');
subject.inc(30,undefined);
subject.inc(30,10);
subject.inc(40,undefined);
subject.inc(40,10);
subject.inc(20,undefined);
subject.inc(20,10);
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":"text content"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"pathContent":{"file1":"text content"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":""}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"},"pathContent":{"file1":"text content"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
mock({"path/fileExists":{"file":"sample text"}});
	subject.fileTest("path/fileExists","pathContent/file1");
mock.restore();
subject.format("","",{"shouldNormalize":true});
subject.format("","","");
subject.blackListNumber("9191234567");
subject.blackListNumber("1234919567");
